---
language: python
sudo: required
dist: xenial

python:
- "3.7"

matrix:
  fast_finish: true

install:
- pip install -r testing-requirements.txt
- pip install .

script:
- tests/run_tests.sh

jobs:
  include:
  - stage: format-check
    python:
    - "3.6"
    install:
    - pip install black
    script:
    - black --check --diff .

deploy:
- provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never